# Generated by Django 4.0.6 on 2022-07-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_specs_horsepower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specs',
            name='horsepower',
            field=models.CharField(max_length=6),
        ),
    ]
